### PR TITLE
Added a Plate Toss Game

### PR DESCRIPTION
**Pull request by thomasayele17**

### CODE REVIEW

**Comment by fstonedahl** [comment]
You didn't commit your changes to the Launcher class to allow your game to actually be played... please fix this and commit/push again.

**Comment by thomasayele17** [comment]
Hello,

Okay thank you very much. I will get on it as soon as the wifi works for my
devices.

Sincerely,
Thomas Ayele

**Comment by thomasayele17** [comment]
Hello,

I have committed my changes and I have committed and pushed it.
Thank you for allowing me to do so.

Sincerely,
Thomas Ayele

**Comment by fstonedahl** [comment]
Looks good now. Toss those plates!

**Pull request closed without merging**
